# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e5cdec1f-86e4-48d1-9bed-efb5422eb37f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e5cdec1f-86e4-48d1-9bed-efb5422eb37f".device = "/dev/disk/by-uuid/e5cdec1f-86e4-48d1-9bed-efb5422eb37f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6C1C-B30F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
