# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7b94efbc-4ee6-48af-bb75-18d263529de6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7b94efbc-4ee6-48af-bb75-18d263529de6" = {
    device = "/dev/disk/by-uuid/7b94efbc-4ee6-48af-bb75-18d263529de6";
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C994-E1E8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
